const skills = [
    "html",
    "css",
    "javascript",
    "typescript",
    "react",
    "nextjs",
    "redux",
    "tailwind",
    "bootstrap",
    "nodejs",
    "express",
    "nestjs",
    "java",
    "spring",
    "springboot",
    "python",
    "django",
    "flask",
    "sql",
    "mysql",
    "postgresql",
    "mongodb",
    "redis",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "jenkins",
    "github actions",
    "numpy",
    "pandas",
    "matplotlib",
    "tensorflow",
    "pytorch",
    "scikit-learn",
    "machine learning",
    "deep learning",
    "git",
    "github",
    "postman",
    "linux",
    "rest api",
    "graphql"
  ];
  
  module.exports = skills;